### ISSUE TITLE
How do I run the mainbomb.py

### ISSUE THREAD

**Issue by MickeyMouseVR** [ARealWant/Guildbomb-Discord-Bot#27]

**Comment by MickeyMouseVR** [comment]
U said it was easy but idk how to do it

**Comment by MickeyMouseVR** [comment]
Idk how to run mainbomb.py

**Comment by lukehodges** [comment]
Do u have python installed

**Comment by MickeyMouseVR** [comment]
Well I mainly don't know how to start it like how do I start itSent from my T-Mobile 4G LTE Device
-------- Original message --------From: luke hodges ***@***.***> Date: 10/5/21  8:07 AM  (GMT-05:00) To: ARealWant/Guildbomb-Discord-Bot ***@***.***> Cc: MickeyMouseVR ***@***.***>, Author ***@***.***> Subject: Re: [ARealWant/Guildbomb-Discord-Bot] How do I run the mainbomb.py (#27) 
Do u have python installed

**Comment by MickeyMouseVR** [comment]
Also u said easy but never pointed out how to do itSent from my T-Mobile 4G LTE Device
-------- Original message --------From: luke hodges ***@***.***> Date: 10/5/21  8:07 AM  (GMT-05:00) To: ARealWant/Guildbomb-Discord-Bot ***@***.***> Cc: MickeyMouseVR ***@***.***>, Author ***@***.***> Subject: Re: [ARealWant/Guildbomb-Discord-Bot] How do I run the mainbomb.py (#27) 
Do u have python installed

**Comment by MickeyMouseVR** [comment]
No whySent from my T-Mobile 4G LTE Device
-------- Original message --------From: luke hodges ***@***.***> Date: 10/5/21  8:07 AM  (GMT-05:00) To: ARealWant/Guildbomb-Discord-Bot ***@***.***> Cc: MickeyMouseVR ***@***.***>, Author ***@***.***> Subject: Re: [ARealWant/Guildbomb-Discord-Bot] How do I run the mainbomb.py (#27) 
Do u have python installed

**Comment by lukehodges** [comment]
You need to install python to run a pyhon file. Then find the file and right click the folder and do "open in terminal". Then type "python the_name_of_thr_file.py:

**Comment by MickeyMouseVR** [comment]
It doesn't say open in terminal when I do itSent from my T-Mobile 4G LTE Device
-------- Original message --------From: luke hodges ***@***.***> Date: 10/6/21  2:49 AM  (GMT-05:00) To: ARealWant/Guildbomb-Discord-Bot ***@***.***> Cc: MickeyMouseVR ***@***.***>, Author ***@***.***> Subject: Re: [ARealWant/Guildbomb-Discord-Bot] How do I run the mainbomb.py (#27) 
You need to install python to run a pyhon file. Then find the file and right click the folder and do "open in terminal". Then type "python the_name_of_thr_file.py:

**Comment by MagonYT** [comment]
> I found another code and added it to my bot and it has same commands so I'm done now thank you for the help though!Sent from my T-Mobile 4G LTE Device -------- Original message --------From: luke hodges ***@***.***> Date: 10/6/21 2:49 AM (GMT-05:00) To: ARealWant/Guildbomb-Discord-Bot ***@***.***> Cc: MickeyMouseVR ***@***.***>, Author ***@***.***> Subject: Re: [ARealWant/Guildbomb-Discord-Bot] How do I run the mainbomb.py (#27) You need to install python to run a pyhon file. Then find the file and right click the folder and do "open in terminal". Then type "python the_name_of_thr_file.py: —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

we didnt need to know you were on a T-Mobile 4G LTE Device

**Comment by ARealWant** [comment]
Fixed this with Guildbomb 4.0.
