### ISSUE TITLE
how can i run mainbomb.py

### ISSUE THREAD

**Issue by GlitchSlime** [ARealWant/Guildbomb-Discord-Bot#29]
well, i added all of those all right, but i can't run it with node . and things

**Comment by shadawcraw** [comment]
This isn't a javascript project, you're not supposed to run it with `node`, but with the python interpreter. To run the file run `python mainbomb.py` for windows, or `python3 mainbomb.py` for linux (if `python` doesn't already run python 3.8 or higher)

**Comment by Dukeatron** [comment]
@GlitchSlime here are some instructions for each OS:

Windows:

1. Download Python from the official site
2. Restart PowerShell (or `cmd`)
3. Run `pip install discord.py`.
4. Download this repository
5. Go into the `Guildbomb` directory and run `python mainbomb.py`
6. Enjoy!

MacOS:

1. Install Python from the official site
2. Run installer
3. Open iTerm or any other terminal emulator
4. Download this repository, and `cd` into the `Guildbomb` directory
5. Then run `python3 install discord`
6. Then run another command called `python3 mainbomb.py`

Linux:

Similar to MacOS

**Comment by GlitchSlime** [comment]
Thanks even though i have figured it out 2 days after asking this question
