### ISSUE TITLE
Getting this issue, cannot find the path specified "entire raid"

### ISSUE THREAD

**Issue by ServerDummy** [ARealWant/Guildbomb-Discord-Bot#30]
![image](https://user-images.githubusercontent.com/63013446/141019061-e249dff2-ad99-4f90-b086-612e1b3f4e37.png)
![image](https://user-images.githubusercontent.com/63013446/141019093-3af01212-d4c7-4bbc-836b-e437ac4f0214.png)

**Comment by ARealWant** [comment]
Fixed this with Guildbomb 4.0.
