### ISSUE TITLE
YOU ARE LITERALLY PROVIDING RAIDERS SOURCE CODE

### ISSUE THREAD

**Issue by pogrammar** [ARealWant/Guildbomb-Discord-Bot#36]
I respect you giving people knowledge of how easy it is to destroy a discord server, **but seriously reconsider what you are doing.**

This repo has a **LOT** of forks, a **LOT** of stars, and the **issue titles make it evident** that people are using this as **source code.**

**Request you to not delete this, but make it private, so that this doesn't promote harmful bots, and raiding**

**Comment by Tabletop472372** [comment]
Mald 😪

**Comment by TacoError** [comment]
Cope

**Comment by MagonYT** [comment]
ratio
