### ISSUE TITLE
issue with data.py

### ISSUE THREAD

**Issue by JackGreen33** [ARealWant/Guildbomb-Discord-Bot#37]
hello, when i try to open/edit data.py it opens the cmd for a split second and it closes it, how can i fix?

**Comment by NHH6035** [comment]
you have to use python idle,. you can search for it and then you will go to file, open and find the data file
idle is for editing lines in a file, and running them in cmd with python commands runs them.

**Comment by ARealWant** [comment]
Fixed this with Guildbomb 4.0.
